### ISSUE TITLE
refactor: migrate to a db

### ISSUE THREAD

**Issue by polarhive** [acmpesuecc/pasta#6]
### Currently this pastebin plays well with small textfiles. Migrate the storage layer to `sqlite`

- [ ] Ensure pastes are properly persisted in the database instead of text files on a filesystem.
- [ ] Implement `CRUD` (Create, Read, Update, Delete) operations.
- [ ] Migration script that convert existing pastes from text files into the new `SQLite` database structure
- [ ] Edge cases such as large pastes or database connection issues should be handled gracefully.
- [ ] Benchmark performance and ensure there's no significant difference compared to the current text file-based approach.

> Consider using (say `gorm` for Go) to simplify database interactions.

Explain your schema as well before working on this issue.

**Comment by rithulkamesh** [comment]
can I get assigned to this?

schema:

```go
type Paste struct {
	ID        string
	Content   string
	CreatedAt time.Time
}
```

Allows me to lookup `/data/:id` and see if there's content, else 404

**Comment by polarhive** [comment]
!assign @rithulkamesh

**Comment by rithulkamesh** [comment]
https://github.com/acmpesuecc/pasta/pull/7

**Comment by polarhive** [comment]
![image](https://github.com/user-attachments/assets/33a7fc95-aac8-41a5-acce-c0196886228d)

**Comment by polarhive** [comment]
!extend 30

**Comment by polarhive** [comment]
!deassign

**Comment by polarhive** [comment]
!assign @rithulkamesh 45

**Comment by rithulkamesh** [comment]
- [x] Ensure pastes are properly persisted in the database instead of text files on a filesystem.
- [x] Implement CRUD (Create, Read, Update, Delete) operations. (ORM)
- [x] Migration script that convert existing pastes from text files into the new SQLite database structure
- [~] Edge cases such as large pastes or database connection issues should be handled gracefully.
- [x] Migrate to a framework (echo)
- [x] Routes for CRUD 
- [ ] Benchmark performance and ensure there's no significant difference compared to the current text file-based approach.

**Comment by polarhive** [comment]
!extend 30

**Comment by polarhive** [comment]
!deassign

**Comment by polarhive** [comment]
will review later manually
